script: ./ci.sh

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
  - language: go
    go: 1.9
    before_script: cd go
  - language: node_js
    node_js: 9
    before_script: cd js
  - language: python
    python: 2.7
    before_script: cd python
  - language: python
    python: 3.6
    before_script: cd python
  - language: ruby
    rvm: 2.4.2
    before_script: cd ruby
  - language: ruby
    rvm: 2.2.2
    before_script: cd ruby
  - language: rust
    rust: stable
    before_script: cd rust
  - language: rust
    rust: nightly
    env: RUST_FEATURES="--no-default-features"
    before_script: cd rust

